# Generated by Django 4.2.2 on 2023-06-08 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guru', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sekolah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=255, null=True)),
                ('tingkat', models.CharField(blank=True, choices=[('SD', 'Sekolah Dasar'), ('SMP', 'Sekolah Menengah Pertama'), ('SMA', 'Sekolah Menengah Atas'), ('SMK', 'Sekolah Menengah Kejuruan')], max_length=3, null=True, verbose_name='Tingkat Sekolah')),
                ('tingkat_verbose', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tingkat Sekolah (Lengkap)')),
                ('npsn', models.CharField(blank=True, max_length=8, null=True)),
                ('alamat', models.CharField(blank=True, max_length=255, null=True)),
                ('kode_pos', models.CharField(blank=True, max_length=5, null=True)),
                ('no_telepon', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nomor Telepon')),
                ('kelurahan', models.CharField(blank=True, max_length=50, null=True)),
                ('kecamatan', models.CharField(blank=True, max_length=50, null=True)),
                ('kota', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kota/Kabupaten')),
                ('provinsi', models.CharField(blank=True, max_length=50, null=True)),
                ('website', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('kepsek', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='is_kepsek', to='guru.guru', verbose_name='Kepala Sekolah')),
            ],
            options={
                'verbose_name': 'Informasi Sekolah',
            },
        ),
    ]
