# Generated by Django 4.2.2 on 2023-06-08 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TahunPelajaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mulai', models.CharField(max_length=4, verbose_name='Tahun Mulai')),
                ('akhir', models.CharField(max_length=4, verbose_name='Tahun Berakhir')),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(editable=False, max_length=255, null=True)),
                ('semester', models.CharField(choices=[('Ganjil', 'Ganjil'), ('Genap', 'Genap')], max_length=6)),
                ('is_active', models.BooleanField(default=False)),
                ('tahun_pelajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester', to='sekolah.tahunpelajaran')),
            ],
        ),
    ]
