# Generated by Django 4.2.2 on 2023-06-08 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0002_tahunpelajaran_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ekskul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('jenis', models.CharField(choices=[('Kepemimpinan', 'Kepemimpinan'), ('Keagamaan', 'Keagamaan'), ('Kesenian', 'Kesenian'), ('Olahraga', 'Olahraga'), ('Lain-Lain', 'Lain-Lain')], max_length=255, verbose_name='Jenis Ekskul')),
            ],
        ),
        migrations.CreateModel(
            name='Jurusan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255, verbose_name='Nama Lengkap')),
                ('singkat', models.CharField(blank=True, max_length=10, null=True, verbose_name='Nama Singkat')),
            ],
        ),
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tingkat', models.CharField(choices=[('10', '10'), ('11', '11'), ('12', '12')], max_length=3)),
                ('kelas', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('nama', models.CharField(blank=True, editable=False, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KKM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pengetahuan', models.SmallIntegerField(default=0, verbose_name='KKM Pengetahuan')),
                ('keterampilan', models.SmallIntegerField(default=0, verbose_name='KKM Keterampilan')),
            ],
        ),
        migrations.CreateModel(
            name='MataPelajaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255, verbose_name='Nama Mata Pelajaran')),
                ('singkat', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Nama Singkat Mata Pelajaran')),
                ('kelompok', models.CharField(choices=[('NA', 'Normatif Adaptif'), ('WS', 'Kejuruan'), ('MULOK', 'Muatan Lokal')], max_length=5, verbose_name='Kelompok Mata Pelajaran')),
            ],
        ),
        migrations.CreateModel(
            name='Rapor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rapor', models.TextField(null=True, verbose_name='Lokasi PDF Rapor')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapor', to='sekolah.semester')),
            ],
        ),
    ]
