# Generated by Django 4.2.2 on 2023-06-08 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siswa', '0001_initial'),
        ('guru', '0001_initial'),
        ('sekolah', '0003_ekskul_jurusan_kelas_kkm_matapelajaran_rapor'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapor',
            name='siswa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rapor', to='siswa.siswa'),
        ),
        migrations.AddField(
            model_name='kkm',
            name='matapelajaran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kkm', to='sekolah.matapelajaran'),
        ),
        migrations.AddField(
            model_name='kkm',
            name='tahun_pelajaran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kkm', to='sekolah.tahunpelajaran'),
        ),
        migrations.AddField(
            model_name='kelas',
            name='jurusan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kelas', to='sekolah.jurusan'),
        ),
        migrations.AddField(
            model_name='kelas',
            name='matapelajaran',
            field=models.ManyToManyField(blank=True, related_name='kelas', to='sekolah.matapelajaran'),
        ),
        migrations.AddField(
            model_name='kelas',
            name='tahun_pelajaran',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kelas', to='sekolah.tahunpelajaran'),
        ),
        migrations.AddField(
            model_name='kelas',
            name='walikelas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kelas', to='guru.guru'),
        ),
    ]
