# Generated by Django 4.2.2 on 2023-07-09 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0004_rapor_siswa_kkm_matapelajaran_kkm_tahun_pelajaran_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matapelajaran',
            name='kelompok',
            field=models.CharField(choices=[('NA', 'Normatif Adaptif'), ('KJ', 'Kejuruan'), ('MULOK', 'Muatan Lokal')], max_length=5, verbose_name='Kelompok Mata Pelajaran'),
        ),
    ]
