# Generated by Django 4.2.2 on 2023-07-10 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0005_alter_matapelajaran_kelompok'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kkm',
            name='keterampilan',
            field=models.SmallIntegerField(verbose_name='KKM Keterampilan'),
        ),
        migrations.AlterField(
            model_name='kkm',
            name='pengetahuan',
            field=models.SmallIntegerField(verbose_name='KKM Pengetahuan'),
        ),
    ]
