# Generated by Django 4.2.2 on 2023-07-10 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0006_alter_kkm_keterampilan_alter_kkm_pengetahuan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kkm',
            name='keterampilan',
            field=models.SmallIntegerField(default=0, verbose_name='KKM Keterampilan'),
        ),
        migrations.AlterField(
            model_name='kkm',
            name='pengetahuan',
            field=models.SmallIntegerField(default=0, verbose_name='KKM Pengetahuan'),
        ),
    ]
