# Generated by Django 4.2.2 on 2023-07-11 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0007_alter_kkm_keterampilan_alter_kkm_pengetahuan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jurusan',
            name='nama',
            field=models.CharField(max_length=50, verbose_name='Nama Lengkap'),
        ),
        migrations.AlterField(
            model_name='matapelajaran',
            name='nama',
            field=models.CharField(max_length=50, verbose_name='Nama Mata Pelajaran'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='nama',
            field=models.CharField(editable=False, max_length=10, null=True),
        ),
    ]
