# Generated by Django 4.2.2 on 2023-07-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siswa', '0003_alter_siswa_agama_alter_siswa_alamat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siswa',
            name='alamat',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='sekolah_asal',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='tempat_lahir',
            field=models.CharField(max_length=50),
        ),
    ]
