# Generated by Django 4.2.2 on 2023-06-08 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('nip', models.CharField(max_length=18, unique=True, verbose_name='Nomor Induk')),
                ('nama', models.CharField(max_length=255)),
                ('nama_gelar', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('gender', models.CharField(choices=[('P', 'Pria'), ('W', 'Wanita')], default='P', max_length=1, verbose_name='Jenis Kelamin')),
                ('tempat_lahir', models.CharField(max_length=255, null=True)),
                ('tanggal_lahir', models.DateField(null=True)),
                ('agama', models.CharField(max_length=255, null=True)),
                ('alamat', models.CharField(max_length=255, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('first_login', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_walikelas', models.BooleanField(default=True, verbose_name='Walikelas')),
                ('is_staftu', models.BooleanField(default=True, verbose_name='Staf TU')),
                ('is_active', models.BooleanField(default=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar/guru/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Gelar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tingkat_gelar', models.CharField(choices=[('A.P.', 'Diploma 1'), ('A.Ma.', 'Diploma 2'), ('A.Md.', 'Diploma 3'), ('A.', 'Diploma 4'), ('S.', 'Sarjana'), ('M.', 'Magister'), ('Dr.', 'Doktor')], max_length=5)),
                ('verbose_tingkat', models.CharField(blank=True, max_length=255, null=True)),
                ('jurusan', models.CharField(choices=[('Administrasi', (('A.B.', 'Administrasi Bisnis'), ('Pn.', 'Administrasi Fiskal'), ('Adm.', 'Administrasi Negara'), ('A.P.', 'Administrasi Perkantoran'), ('I.P.', 'Ilmu Perpustakaan'))), ('Ekonomi', (('Ak.', 'Akuntansi'), ('E.', 'Ilmu Ekonomi'), ('E.', 'Manajemen'))), ('Kesehatan', (('Farm.', 'Farmasi'), ('Gz.', 'Ilmu Gizi'), ('Keb.', 'Kebidanan'), ('Ked.', 'Kedokteran'), ('K.G.', 'Kedokteran Gigi'), ('K.H.', 'Kedokteran Hewan'), ('Kep.', 'Keperawatan'), ('K.M.', 'Kesehatan Masyarakat'), ('Psi.', 'Psikologi'))), ('Kesenian', (('Ds.', 'Desain Komunikasi Visual'), ('Ds.', 'Desain Produk'), ('Sn.', 'Seni Kriya'), ('Sn.', 'Seni Musik'), ('Sn.', 'Seni Rupa'), ('Sn.', 'Seni Tari'))), ('Ilmu Budaya', (('Hum.', 'Humaniora'), ('Fil.', 'Filsafat'), ('Hum.', 'Ilmu Sejarah'), ('Par.', 'Pariwisata'), ('S.', 'Sastra'))), ('Matematika & IPA', (('Si.', 'Astronomi'), ('Si.', 'Biologi'), ('Si.', 'Fisika'), ('Si.', 'Geofisika'), ('Si.', 'Geologi'), ('Si.', 'Kimia'), ('Si.', 'Matematika'), ('Stat.', 'Statistika'))), ('Pendidikan', (('Pd.', 'Bimbingan Konseling'), ('Pd.', 'Kebijakan Pendidikan'), ('Pd.', 'Manajemen Pendidikan'), ('Pd.', 'Pendidikan Luar Biasa'), ('Pd.', 'Pendidikan Luar Sekolah'), ('Pd.', 'PGPAUD'), ('Pd.', 'PGSD'), ('Pd.', 'Teknologi Pendidikan'))), ('Pertanian', (('P.', 'Agribisnis'), ('P.', 'Agroteknologi'), ('P.', 'Ilmu Tanah'), ('Hut.', 'Kehutanan'), ('Pi.', 'Perikanan'), ('T.P.', 'Teknologi Hasil Pertanian'))), ('Sosial', (('Ant.', 'Antropologi Sosial'), ('H.Int.', 'Hubungan Internasional'), ('H.', 'Hukum'), ('Si.', 'Geografi'), ('Sos.', 'Ilmu Kesejahteraan Sosial'), ('I.Kom.', 'Ilmu Komunikasi'), ('IP.', 'Ilmu Politik'), ('Sos.', 'Kriminologi'), ('Sos.', 'Sosiologi'))), ('Teknik', (('Ars.', 'Arsitektur'), ('Kom.', 'Ilmu Komputer'), ('Kom.', 'Sistem Informasi'), ('Kom.', 'Teknik Informatika'), ('T.', 'Teknik Bioproses'), ('T.', 'Teknik Elektro'), ('T.', 'Teknik Elektronika'), ('T.', 'Teknik Fisika'), ('T.', 'Teknik Geodesi'), ('T.', 'Teknik Geofisika'), ('T.', 'Teknik Geologi'), ('T.', 'Teknik Industri'), ('T.', 'Teknik Kelautan'), ('T.', 'Teknik Kimia'), ('T.', 'Teknik Telekomunikasi'), ('T.', 'Teknik Lingkungan'), ('T.', 'Teknik Metalurgi'), ('T.', 'Teknik Mekatronika'), ('T.', 'Teknik Mesin'), ('T.', 'Teknik Nuklir'), ('T.', 'Teknik Otomotif'), ('T.', 'Teknik Permniyakan'), ('T.', 'Teknik Pertambangan'), ('T.', 'Teknik Sipil'), ('T.', 'Teknik Transportasi Laut')))], max_length=255)),
                ('verbose_jurusan', models.CharField(blank=True, max_length=255, null=True)),
                ('universitas', models.CharField(max_length=255)),
                ('gelar', models.CharField(blank=True, max_length=255, null=True)),
                ('guru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guru.guru')),
            ],
        ),
    ]
