# Generated by Django 4.2.2 on 2023-07-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guru', '0002_alter_gelar_jurusan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guru',
            name='agama',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='guru',
            name='alamat',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='guru',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='guru',
            name='nama',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='guru',
            name='nama_gelar',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='guru',
            name='tempat_lahir',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
