# Generated by Django 4.2.2 on 2023-07-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guru', '0004_alter_guru_nama_gelar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guru',
            name='nama_gelar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
