# Generated by Django 4.2.2 on 2023-07-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guru', '0006_alter_guru_agama_alter_guru_alamat_alter_guru_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guru',
            name='agama',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='guru',
            name='alamat',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='guru',
            name='tempat_lahir',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
