# Generated by Django 4.2.2 on 2023-08-03 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guru', '0007_alter_guru_agama_alter_guru_alamat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guru',
            name='is_staftu',
            field=models.BooleanField(default=False, verbose_name='Staf TU'),
        ),
    ]
